package cn.com.yusys.yscrm.cust.person.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-11T14:30:54.257+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CstRelInfQrySvcSrvBindingQSService",
                  wsdlLocation = "file:/C:/Users/USER/AppData/Local/Temp/tempdir8704733379480655643.tmp/P00001003049_1.wsdl",
                  targetNamespace = "http://www.whrcbank.com")
public class CstRelInfQrySvcSrvBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.whrcbank.com", "CstRelInfQrySvcSrvBindingQSService");
    public final static QName CstRelInfQrySvcSrvBindingQSPort = new QName("http://www.whrcbank.com", "CstRelInfQrySvcSrvBindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/USER/AppData/Local/Temp/tempdir8704733379480655643.tmp/P00001003049_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CstRelInfQrySvcSrvBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/USER/AppData/Local/Temp/tempdir8704733379480655643.tmp/P00001003049_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CstRelInfQrySvcSrvBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CstRelInfQrySvcSrvBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CstRelInfQrySvcSrvBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CstRelInfQrySvcSrvBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CstRelInfQrySvcSrvBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CstRelInfQrySvcSrvBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CstRelInfQrySvcSrvPortType
     */
    @WebEndpoint(name = "CstRelInfQrySvcSrvBindingQSPort")
    public CstRelInfQrySvcSrvPortType getCstRelInfQrySvcSrvBindingQSPort() {
        return super.getPort(CstRelInfQrySvcSrvBindingQSPort, CstRelInfQrySvcSrvPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CstRelInfQrySvcSrvPortType
     */
    @WebEndpoint(name = "CstRelInfQrySvcSrvBindingQSPort")
    public CstRelInfQrySvcSrvPortType getCstRelInfQrySvcSrvBindingQSPort(WebServiceFeature... features) {
        return super.getPort(CstRelInfQrySvcSrvBindingQSPort, CstRelInfQrySvcSrvPortType.class, features);
    }

}
