package cn.com.yusys.yscrm.cust.person.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.security.NoSuchAlgorithmException;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-11T14:30:54.247+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.whrcbank.com", name = "CstRelInfQrySvcSrvPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CstRelInfQrySvcSrvPortType {

    @WebMethod(operationName = "CstRelInfQry", action = "urn:CstRelInfQry")
    public void cstRelInfQry(
        @WebParam(partName = "paramCstRelInfQryReqHeader", name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        SysMsgHeader paramCstRelInfQryReqHeader,
        @WebParam(partName = "paramCstRelInfQryReqBody", name = "request", targetNamespace = "http://www.whrcbank.com/service/bd/R17601003044R")
        SrvReqBody paramCstRelInfQryReqBody,
        @WebParam(partName = "paramCstRelInfQryResHeader", mode = WebParam.Mode.OUT, name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        javax.xml.ws.Holder<SysMsgHeader> paramCstRelInfQryResHeader,
        @WebParam(partName = "paramCstRelInfQryResBody", mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://www.whrcbank.com/service/bd/R17601003044R")
        javax.xml.ws.Holder<SrvResBody> paramCstRelInfQryResBody
    ) throws NoSuchAlgorithmException;
}
