
package cn.com.yusys.yscrm.cust.person.util;

import java.util.Map;

import javax.xml.ws.Endpoint;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Service;





/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-11T14:30:54.253+08:00
 * Generated source version: 3.3.0
 *
 */
//
@Service
public class CstRelInfQrySvcSrvPortType_CstRelInfQrySvcSrvBindingQSPort_Server implements ApplicationListener<ContextRefreshedEvent>{
	@Autowired
	Environment env;
	@Autowired
	CstRelInfQrySvcSrvBindingQSPortImpl cstService;
    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
//			System.out.println("信息查询接口启动");
////	        Object implementor = new CstRelInfQrySvcSrvBindingQSPortImpl();
//	        String address = "http://"+env.getProperty("spring.datasource.ip")+":8014/crm";
//	        Endpoint.publish(address, cstService);
//			System.out.println("\n\n\n\n\n************************信息查询接口就绪");
	}

	
}
