
package cn.com.yusys.yscrm.salesoppor.sendRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRMAcctDtQrySvcSrvPortType", targetNamespace = "http://www.whrcbank.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface CRMAcctDtQrySvcSrvPortType {


    /**
     * 
     * @param paramCRMAcctDtQryReqHeader
     * @param paramCRMAcctDtQryReqBody
     * @param paramCRMAcctDtQryResHeader
     * @param paramCRMAcctDtQryResBody
     */
    @WebMethod(operationName = "CRMAcctDtQry", action = "urn:CRMAcctDtQry")
    public void crmAcctDtQry(
        @WebParam(name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true, partName = "paramCRMAcctDtQryReqHeader")
        SysMsgHeader paramCRMAcctDtQryReqHeader,
        @WebParam(name = "request", targetNamespace = "http://www.whrcbank.com/service/bd/R11002003094", partName = "paramCRMAcctDtQryReqBody")
        SrvReqBody paramCRMAcctDtQryReqBody,
        @WebParam(name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true, mode = WebParam.Mode.OUT, partName = "paramCRMAcctDtQryResHeader")
        Holder<SysMsgHeader> paramCRMAcctDtQryResHeader,
        @WebParam(name = "response", targetNamespace = "http://www.whrcbank.com/service/bd/R11002003094", mode = WebParam.Mode.OUT, partName = "paramCRMAcctDtQryResBody")
        Holder<SrvResBody> paramCRMAcctDtQryResBody);

}
