
package cn.com.yusys.yscrm.salesoppor.sendRequest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRMAcctDtQrySvcSrvBindingQSService", targetNamespace = "http://www.whrcbank.com", wsdlLocation = "http://22.1.32.54:8111/services/P00002003098?wsdl")
public class CRMAcctDtQrySvcSrvBindingQSService
    extends Service
{
    private static final String WHRCBANK = "http://www.whrcbank.com";
    private final static URL CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_EXCEPTION;
    private final static QName CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_QNAME = new QName(WHRCBANK, "CRMAcctDtQrySvcSrvBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://22.1.32.54:8111/services/P00002003098?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_WSDL_LOCATION = url;
        CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_EXCEPTION = e;
    }

    public CRMAcctDtQrySvcSrvBindingQSService() {
        super(__getWsdlLocation(), CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_QNAME);
    }

    public CRMAcctDtQrySvcSrvBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_QNAME, features);
    }

    public CRMAcctDtQrySvcSrvBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_QNAME);
    }

    public CRMAcctDtQrySvcSrvBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_QNAME, features);
    }

    public CRMAcctDtQrySvcSrvBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMAcctDtQrySvcSrvBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRMAcctDtQrySvcSrvPortType
     */
    @WebEndpoint(name = "CRMAcctDtQrySvcSrvBindingQSPort")
    public CRMAcctDtQrySvcSrvPortType getCRMAcctDtQrySvcSrvBindingQSPort() {
        return super.getPort(new QName(WHRCBANK, "CRMAcctDtQrySvcSrvBindingQSPort"), CRMAcctDtQrySvcSrvPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMAcctDtQrySvcSrvPortType
     */
    @WebEndpoint(name = "CRMAcctDtQrySvcSrvBindingQSPort")
    public CRMAcctDtQrySvcSrvPortType getCRMAcctDtQrySvcSrvBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName(WHRCBANK, "CRMAcctDtQrySvcSrvBindingQSPort"), CRMAcctDtQrySvcSrvPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_EXCEPTION!= null) {
            throw CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_EXCEPTION;
        }
        return CRMACCTDTQRYSVCSRVBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
