package cn.com.yusys.yscrm.info.remind.fileTrans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-16T10:12:21.808+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.whrcbank.com", name = "RealtimeTransJobSrvSrvPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RealtimeTransJobSrvSrvPortType {

    @WebMethod(operationName = "RealtimeTransJob", action = "urn:RealtimeTransJob")
    public void realtimeTransJob(
        @WebParam(partName = "paramRealtimeTransJobReqHeader", name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        SysMsgHeader paramRealtimeTransJobReqHeader,
        @WebParam(partName = "paramRealtimeTransJobReqBody", name = "request", targetNamespace = "http://www.whrcbank.com/service/bd/R14002000312")
        SrvReqBody paramRealtimeTransJobReqBody,
        @WebParam(partName = "paramRealtimeTransJobResHeader", mode = WebParam.Mode.OUT, name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        javax.xml.ws.Holder<SysMsgHeader> paramRealtimeTransJobResHeader,
        @WebParam(partName = "paramRealtimeTransJobResBody", mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://www.whrcbank.com/service/bd/R14002000312")
        javax.xml.ws.Holder<SrvResBody> paramRealtimeTransJobResBody
    );
}
