
package cn.com.yusys.yscrm.custservice.util;

import javax.xml.ws.Endpoint;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Service;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T10:21:26.575+08:00
 * Generated source version: 3.3.0
 *
 */

@Service
public class CstRsInRgsSvcSrvPortType_CstRsInRgsSvcSrvBindingQSPort_Server implements ApplicationListener<ContextRefreshedEvent>{
	@Autowired
	Environment env;
	@Autowired
	CstRsInRgsSvcSrvBindingQSPortImpl cstRsInRgsSvcSrvBindingQSPortImpl;
	@Override
	public void onApplicationEvent(ContextRefreshedEvent event) {
//		System.out.println("客户反馈信息登记接口启动");
////        Object implementor = new CstRsInRgsSvcSrvBindingQSPortImpl();
//        String address = "http://"+env.getProperty("spring.datasource.ip")+":8015/crm";
//        Endpoint.publish(address, cstRsInRgsSvcSrvBindingQSPortImpl);
//		System.out.println("\n\n\n\n\n************************客户反馈信息登记接口就绪");
	}
}
