package cn.com.yusys.yscrm.custservice.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T10:21:26.579+08:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CstRsInRgsSvcSrvBindingQSService",
                  wsdlLocation = "file:/C:/Users/USER/AppData/Local/Temp/tempdir8748282370806659265.tmp/P00002003050_1.wsdl",
                  targetNamespace = "http://www.whrcbank.com")
public class CstRsInRgsSvcSrvBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.whrcbank.com", "CstRsInRgsSvcSrvBindingQSService");
    public final static QName CstRsInRgsSvcSrvBindingQSPort = new QName("http://www.whrcbank.com", "CstRsInRgsSvcSrvBindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/USER/AppData/Local/Temp/tempdir8748282370806659265.tmp/P00002003050_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CstRsInRgsSvcSrvBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/USER/AppData/Local/Temp/tempdir8748282370806659265.tmp/P00002003050_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CstRsInRgsSvcSrvBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CstRsInRgsSvcSrvBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CstRsInRgsSvcSrvBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CstRsInRgsSvcSrvBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CstRsInRgsSvcSrvBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CstRsInRgsSvcSrvBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CstRsInRgsSvcSrvPortType
     */
    @WebEndpoint(name = "CstRsInRgsSvcSrvBindingQSPort")
    public CstRsInRgsSvcSrvPortType getCstRsInRgsSvcSrvBindingQSPort() {
        return super.getPort(CstRsInRgsSvcSrvBindingQSPort, CstRsInRgsSvcSrvPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CstRsInRgsSvcSrvPortType
     */
    @WebEndpoint(name = "CstRsInRgsSvcSrvBindingQSPort")
    public CstRsInRgsSvcSrvPortType getCstRsInRgsSvcSrvBindingQSPort(WebServiceFeature... features) {
        return super.getPort(CstRsInRgsSvcSrvBindingQSPort, CstRsInRgsSvcSrvPortType.class, features);
    }

}
