# 使用数据库时代码自动创建的配置文件，从application.yml中可获取，不使用数据库时可删除该文件
spring:
  datasource:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.16.90.15:1521:sybase
    username: uimp_dev
    password: uimp_dev