package cn.com.yusys.yscrm.salesoppor.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.security.NoSuchAlgorithmException;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-14T11:51:29.959+08:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.whrcbank.com", name = "BsOpInfoRgsSvcSrvPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BsOpInfoRgsSvcSrvPortType {

    @WebMethod(operationName = "BsOpInfoRgs", action = "urn:BsOpInfoRgs")
    public void bsOpInfoRgs(
        @WebParam(partName = "paramBsOpInfoRgsReqHeader", name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        SysMsgHeader paramBsOpInfoRgsReqHeader,
        @WebParam(partName = "paramBsOpInfoRgsReqBody", name = "request", targetNamespace = "http://www.whrcbank.com/service/bd/R17602003046R")
        SrvReqBody paramBsOpInfoRgsReqBody,
        @WebParam(partName = "paramBsOpInfoRgsResHeader", mode = WebParam.Mode.OUT, name = "sysHeader", targetNamespace = "http://www.whrcbank.com/common/header/in", header = true)
        javax.xml.ws.Holder<SysMsgHeader> paramBsOpInfoRgsResHeader,
        @WebParam(partName = "paramBsOpInfoRgsResBody", mode = WebParam.Mode.OUT, name = "response", targetNamespace = "http://www.whrcbank.com/service/bd/R17602003046R")
        javax.xml.ws.Holder<SrvResBody> paramBsOpInfoRgsResBody
    ) throws NoSuchAlgorithmException;
}
