
package cn.com.yusys.yscrm.salesoppor.interfaces;

import javax.xml.ws.Endpoint;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Service;

import cn.com.yusys.yscrm.salesoppor.utils.JdbcUtils;

/**
 * This class was generated by Apache CXF 3.3.0 2019-03-14T11:51:29.968+08:00
 * Generated source version: 3.3.0
 *
 */
@Service
public class BsOpInfoRgsSvcSrvPortType_BsOpInfoRgsSvcSrvBindingQSPort_Server implements ApplicationListener<ContextRefreshedEvent>{
	@Autowired
	Environment env;
	@Autowired
	BsOpInfoRgsSvcSrvBindingQSPortImpl bsOpInfoRgsSvcSrvBindingQSPortImpl;
	
	@Override
	public void onApplicationEvent(ContextRefreshedEvent arg0) {
//		 	System.out.println("商机信息登记启动");
////	        Object implementor = new BsOpInfoRgsSvcSrvBindingQSPortImpl();
//	        String address = "http://"+env.getProperty("spring.datasource.ip")+":8016/crm";
//	        Endpoint.publish(address, bsOpInfoRgsSvcSrvBindingQSPortImpl);
//	        System.out.println("\n\n商机信息登记就绪\n\n");
	}
}
