
package cn.com.yusys.yscrm.salesoppor.fileTrans;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-16T10:12:21.762+08:00
 * Generated source version: 3.3.0
 *
 */
public final class RealtimeTransJobSrvSrvPortType_RealtimeTransJobSrvSrvBindingQSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.whrcbank.com", "RealtimeTransJobSrvSrvBindingQSService");

    private RealtimeTransJobSrvSrvPortType_RealtimeTransJobSrvSrvBindingQSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RealtimeTransJobSrvSrvBindingQSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RealtimeTransJobSrvSrvBindingQSService ss = new RealtimeTransJobSrvSrvBindingQSService(wsdlURL, SERVICE_NAME);
        RealtimeTransJobSrvSrvPortType port = ss.getRealtimeTransJobSrvSrvBindingQSPort();

        {
        System.out.println("Invoking realtimeTransJob...");
        cn.com.yusys.yscrm.salesoppor.fileTrans.SysMsgHeader _realtimeTransJob_paramRealtimeTransJobReqHeader = null;
        cn.com.yusys.yscrm.salesoppor.fileTrans.SrvReqBody _realtimeTransJob_paramRealtimeTransJobReqBody = null;
        javax.xml.ws.Holder<cn.com.yusys.yscrm.salesoppor.fileTrans.SysMsgHeader> _realtimeTransJob_paramRealtimeTransJobResHeader = new javax.xml.ws.Holder<cn.com.yusys.yscrm.salesoppor.fileTrans.SysMsgHeader>();
        javax.xml.ws.Holder<cn.com.yusys.yscrm.salesoppor.fileTrans.SrvResBody> _realtimeTransJob_paramRealtimeTransJobResBody = new javax.xml.ws.Holder<cn.com.yusys.yscrm.salesoppor.fileTrans.SrvResBody>();
        port.realtimeTransJob(_realtimeTransJob_paramRealtimeTransJobReqHeader, _realtimeTransJob_paramRealtimeTransJobReqBody, _realtimeTransJob_paramRealtimeTransJobResHeader, _realtimeTransJob_paramRealtimeTransJobResBody);

        System.out.println("realtimeTransJob._realtimeTransJob_paramRealtimeTransJobResHeader=" + _realtimeTransJob_paramRealtimeTransJobResHeader.value);
        System.out.println("realtimeTransJob._realtimeTransJob_paramRealtimeTransJobResBody=" + _realtimeTransJob_paramRealtimeTransJobResBody.value);

        }

        System.exit(0);
    }

}
